blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    userrname:m0nyax
    repo:ToDo
    # edit {username} and {repo} for your environment
    url: https://github.com/MochizukiLab/ToDo.git
